### ISSUE TITLE
Cannot build s2n when -DUSE_OPENSSL=ON

### ISSUE THREAD

**Issue by Hadatko** [awslabs/aws-crt-cpp#406] opened 2022-09-15 13:48 UTC
With command bellow
```bash
AWS_IOT_SDK_FOLDERNAME="aws-iot-device-sdk-cpp"
AWS_IOT_SDK_URL="https://github.com/aws/aws-iot-device-sdk-cpp-v2.git"
AWS_IOT_SDK_VER="1.18.6"

  rm -rf awsbuild &&
  git clone --recursive ${AWS_IOT_SDK_URL} --branch v${AWS_IOT_SDK_VER} ${AWS_IOT_SDK_FOLDERNAME} &&
  mkdir awsbuild &&
  cd awsbuild &&
  cmake -DUSE_OPENSSL=ON \
      -DCMAKE_INSTALL_PREFIX="$(pwd)/../dependencies/aws-iot-device-sdk" \
      -Dcrypto_LIBRARY="$(pwd)/../openssl/libcrypto.a" \
      -Dcrypto_INCLUDE_DIR="$(pwd)/../openssl/include" \
      -DOPENSSL_CRYPTO_LIBRARY="$(pwd)/../openssl/libcrypto.a" \
      -DOPENSSL_INCLUDE_DIR="$(pwd)/../openssl/include" \
      -DCMAKE_BUILD_TYPE="Release" ../${AWS_IOT_SDK_FOLDERNAME} &&
  cmake --build . --target install
```

I am getting this error:
```bash
-- madvise() support detected
-- clone() support detected
-- Found crypto: /home/acrios_cervennka/kseftiky/aeler/atlas-pilot-fw/Firmware/containers/aws-iotsdk/awsbuild/../dependencies/openssl/libcrypto.a  
-- LibCrypto Include Dir: /home/acrios_cervennka/kseftiky/aeler/atlas-pilot-fw/Firmware/containers/aws-iotsdk/dependencies/openssl/include
-- LibCrypto Shared Lib:  crypto_SHARED_LIBRARY-NOTFOUND
-- LibCrypto Static Lib:  crypto_STATIC_LIBRARY-NOTFOUND
Using libcrypto from the cmake path.
CMake Error at /home/acrios_cervennka/kseftiky/aeler/atlas-pilot-fw/Firmware/containers/aws-iotsdk/awsbuild/CMakeFiles/CMakeTmp/CMakeLists.txt:18 (add_executable):
  Target "cmTC_23663" links to target "AWS::crypto" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at crt/aws-crt-cpp/crt/s2n/CMakeLists.txt:496 (try_compile):
  Failed to generate test project build system.


-- Configuring incomplete, errors occurred!
See also "/home/acrios_cervennka/kseftiky/aeler/atlas-pilot-fw/Firmware/containers/aws-iotsdk/awsbuild/CMakeFiles/CMakeOutput.log".
See also "/home/acrios_cervennka/kseftiky/aeler/atlas-pilot-fw/Firmware/containers/aws-iotsdk/awsbuild/CMakeFiles/CMakeError.log".
```

**Comment by sbSteveK** [comment] 2023-02-03 21:46
Running the same commands I'm getting the following results: 
```
-- AWS CRT C++ 0.19.7-dev+f9ad934c
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- The C compiler identification is AppleClang 14.0.0.14000029
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- CMake 3.24.3
CMake Deprecation Warning at crt/aws-c-common/CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0077 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for pthread_mutexattr_init
-- Looking for pthread_mutexattr_init - not found
-- Performing Test HAS_FPIC_FLAG
-- Performing Test HAS_FPIC_FLAG - Success
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Success
-- Performing Test NO_GNU_EXPR
-- Performing Test NO_GNU_EXPR - Success
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Success
-- attempting to use sanitizer list address;undefined
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_CRYPTO_LIBRARY
    OPENSSL_INCLUDE_DIR
    crypto_INCLUDE_DIR
    crypto_LIBRARY
```
The cmake install is succeeding after the build. Please try the latest version of the CRT and if this continues to be an issue, provide which OS/env/version you're using , the full log, and any other details you think may help us reproduce the issue. Thanks!

**Comment by sbSteveK** [comment] 2023-02-03 21:57
Following the directions and commands provided, I successfully built and installed with the following output:
```
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v0.17.30
-- CMake 3.24.3
CMake Deprecation Warning at crt/aws-crt-cpp/crt/aws-c-common/CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0077 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for pthread_mutexattr_init
-- Looking for pthread_mutexattr_init - not found
-- Performing Test HAS_FPIC_FLAG
-- Performing Test HAS_FPIC_FLAG - Success
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Success
-- Performing Test NO_GNU_EXPR
-- Performing Test NO_GNU_EXPR - Success
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Success
-- attempting to use sanitizer list address;undefined
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- attempting to use sanitizer list address;undefined
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_CRYPTO_LIBRARY
    OPENSSL_INCLUDE_DIR
    crypto_INCLUDE_DIR
    crypto_LIBRARY


-- Build files have been written to: /Users/sbstevek/workplace/issue-406-crt-cpp/awsbuild
```

Please provide any logs, your os\version\env details, and any other information that may assist in recreating this issue.

**Comment by Hadatko** [comment] 2023-02-05 08:41
[output.log](https://github.com/awslabs/aws-crt-cpp/files/10610521/output.log)
ubuntu Linux kuhadatko-GL552VW 5.19.0-29-generic #30-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 4 12:14:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

Same output i have on 22.04

**Comment by bretambrose** [comment] 2023-02-07 23:29
I don't know enough about cmake to determine whether or not setting the libcrypto variables directly is an issue (or perhaps it's your openssl install layout, because your library does not appear to be under lib), but the following worked for me on Ubuntu 22.

Openssl
```
cd /tmp
git clone https://github.com/openssl/openssl
cd openssl
git checkout OpenSSL_1_1_1s
CFLAGS=-fPIC ./config --prefix=/tmp/install
make -j
make install
```

SDK
```
cd /tmp
git clone https://github.com/aws/aws-iot-device-sdk-cpp-v2
cd aws-iot-device-sdk-cpp-v2
git checkout v1.18.6
mkdir _build
cd _build
cmake -DCMAKE_PREFIX_PATH=/tmp/install -DUSE_OPENSSL=ON ..
make -j
```

the SDK cmake invocation results in the following output where you can see the custom build of openssl getting picked up:

```
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- AWS CRT C++ v1.18.6
-- CMake 3.22.1
CMake Deprecation Warning at crt/aws-crt-cpp/crt/aws-c-common/CMakeLists.txt:17 (cmake_policy):
  The OLD behavior for policy CMP0077 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Success
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_HAVE_WINAPI_DESKTOP
-- Performing Test AWS_HAVE_WINAPI_DESKTOP - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Success
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Success
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Success
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H
-- Performing Test AWS_HAVE_LINUX_IF_LINK_H - Success
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Looking for pthread_mutexattr_init
-- Looking for pthread_mutexattr_init - not found
-- Performing Test HAS_FPIC_FLAG
-- Performing Test HAS_FPIC_FLAG - Success
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT
-- Performing Test HAS_64BIT_FILE_OFFSET_BY_DEFAULT - Success
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Success
-- Looking for pthread_attr_setaffinity_np
-- Looking for pthread_attr_setaffinity_np - found
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Building SIMD base64 decoder
-- Packaging currently only supported on Fedora.
-- Detected CMAKE_SYSTEM_PROCESSOR as x86_64
-- Detected 64-Bit system
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Enabling SIKEP434R3 assembly code
-- Enabling Kyber_R3 x86_64 optimizations
-- Support for ADX assembly instructions detected
-- madvise() support detected
-- clone() support detected
-- Found crypto: /tmp/install/lib/libcrypto.a  
-- LibCrypto Include Dir: /tmp/install/include
-- LibCrypto Shared Lib:  /tmp/install/lib/libcrypto.so
-- LibCrypto Static Lib:  /tmp/install/lib/libcrypto.a
Using libcrypto from the cmake path.
-- Found OpenSSL: /tmp/install/lib/libcrypto.so (found version "1.1.1s")  
-- Using libcrypto from system: /tmp/install/lib/libcrypto.so
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/aws-iot-device-sdk-cpp-v2/_build
```

The subsequent build is also successful.

**Comment by bretambrose** [comment] 2023-02-14 17:32
Closing absent additional information.

**Closed by bretambrose** 2023-02-14 17:32 UTC
Labels: response-requested, closing-soon
