### ISSUE TITLE
Support for OS versions prior to Windows 8.1

### ISSUE THREAD

**Issue by kankri** [awslabs/aws-crt-cpp#144] opened 2020-06-24 15:40 UTC
I see there is a runtime check for Windows 8.1 in aws-crt-cpp to decide whether ALPN is available or not. I decided to try out how the SDK works out in my Windows 7 environment and noticed the following issues:

* When building on Windows 10 with Visual Studio 2017 I had to add the following setting in `CMakeLists.txt`, otherwise the call to `CertCreateCertificateChainEngine()` would fail:
    ```
    add_definitions(-DWINVER=0x0601 -D_WIN32_WINNT=0x0601)
    ```
    Is this the correct approach? It would be nice to be able to avoid modifying the `CMakeLists.txt` file.
* When trying to use the resulting binary, the connection to port 8883 of the AWS IoT server was disconnected during the TLS handshake. I checked the following 36 hosts resolving to the IoT DNS name and found some of them not supporting TLS 1.0:
    
    | TLS 1 | host                |
    | ------| ------------------- |
    |  no   |   3.248.37.235:8883 |
    |  yes  |  3.248.143.162:8883 |
    |  no   |  18.202.47.175:8883 |
    |  no   | 34.246.240.147:8883 |
    |  no   |  34.247.250.12:8883 |
    |  yes  |  34.248.23.176:8883 |
    |  no   | 34.248.215.173:8883 |
    |  no   | 34.248.219.217:8883 |
    |  yes  |   34.249.33.19:8883 |
    |  no   |  34.249.201.54:8883 |
    |  yes  | 34.251.110.255:8883 |
    |  yes  | 34.251.148.129:8883 |
    |  yes  | 34.253.253.202:8883 |
    |  no   |  34.254.167.26:8883 |
    |  no   |    52.17.220.6:8883 |
    |  yes  |   52.18.188.24:8883 |
    |  no   |   52.19.57.158:8883 |
    |  yes  |  52.19.161.237:8883 |
    |  no   |   52.31.90.196:8883 |
    |  yes  |  52.49.241.208:8883 |
    |  no   |  52.49.244.154:8883 |
    |  yes  |    52.51.157.5:8883 |
    |  no   |   52.208.29.67:8883 |
    |  yes  |  52.208.146.89:8883 |
    |  no   |  52.213.243.33:8883 |
    |  yes  |  52.214.225.79:8883 |
    |  no   |   52.215.86.27:8883 |
    |  yes  |  52.215.100.50:8883 |
    |  yes  |   54.72.137.20:8883 |
    |  yes  |   54.76.92.180:8883 |
    |  no   |  54.154.36.110:8883 |
    |  no   |  54.194.73.139:8883 |
    |  yes  |  54.194.108.62:8883 |
    |  no   |  63.32.148.190:8883 |
    |  yes  | 108.128.37.111:8883 |
    |  yes  |  108.129.67.76:8883 |
    
    Should all servers support TLS 1.0?

**Comment by JonathanHenson** [comment] 2020-06-24 19:10
https://aws.amazon.com/blogs/security/tls-1-2-to-become-the-minimum-for-all-aws-fips-endpoints/

As new services are added, many will be TLS 1.2 or later only. 

I’m checking with IOT on the policy for them.

**Comment by JonathanHenson** [comment] 2020-06-24 19:13
As far as the compiler macros, we’ll probably want to add them to the source files and guard them with a windows version check

**Comment by JonathanHenson** [comment] 2020-06-24 20:13
Support for OS versions is different from what the service supports. We’re currently working on the current behavior from the iot side and will keep you posted. We’ll certainly be fixing the build at the least.

**Comment by JonathanHenson** [comment] 2020-06-24 20:13
Support for OS versions is different from what the service supports. We’re currently working on the current behavior from the iot side and will keep you posted. We’ll certainly be fixing the build at the least.

**Comment by JonathanHenson** [comment] 2020-06-24 20:33
Okay so here’s what I found. 443 is the only port that supports TLS < 1.2. If you don’t have alpn support, you need to use websockets over 443. TLS 1.0 should be supported there. It was a bug caused by a server-side migration that had some of them upgraded to 1.1 only and is currently being rolled back. Hope this helps.

**Comment by JonathanHenson** [comment] 2020-06-24 20:34
The Certificate import should be unnecessary on windows 7 since you can’t use them anyways. For those you’ll want to use traditional IAM credentials.

**Comment by kankri** [comment] 2020-06-25 06:52
> Okay so here’s what I found. 443 is the only port that supports TLS < 1.2

I'm puzzled by this, since I listed above 18 servers which supported TLS 1.0 on port 8883. Why are (only) half of the servers resolved by DNS responding in port 8883 with TLS 1.0 support?

**Comment by kankri** [comment] 2020-06-25 07:23
> The Certificate import should be unnecessary on windows 7 since you can’t use them anyways.

If TLS 1.2 is enabled on Windows 7, it would work on port 8883 so CertCreateCertificateChainEngine() needs to work.

**Comment by kankri** [comment] 2020-06-25 10:50
If I understand correctly, your suggestion is to use websockets for older Windows versions and normal certificate authentication for current Windows versions? I think this requires us to create two authentication flows to get the security tokens for websockets?

Looking at the `--use_websocket` option in `basic_pub_sub` sample, it seems to rely on the predefined environment variables to contain correct credentials. This obviously doesn't work outside of dev environments. I think the idea is to use custom credentials provider in other cases? Is there any sample code to show hows this works?

**Comment by JonathanHenson** [comment] 2020-06-29 19:27
Here's the plan. We'll fix the windows 7 build. We're currently trying to find a windows 7 machine to test on, but will be fixing the build as soon as we can.

The --use_websocket option should be using the default credentials provider chain, which uses env variables, .config/.credentials files, ec2 imds, ecs creds provider, and process credentials provider until it finds creds. However, you'll probably want to use something else like cognito-identity, or IOT's x.509 credentials provider. Happy to help you sort through your options there. 

If you can get tls1.2 working on windows 7, you can also just use port 8883 instead with your current certificate mechanisms.

**Comment by justinboswell** [comment] 2020-07-09 16:35
Core library now enforces Win7 API, going to test this with I/O next and make sure all the TLS stuff still works as expected.

**Comment by kankri** [comment] 2020-07-10 11:39
I see you made Windows 7 support behind a flag. Did you discover some problems having it on by default?

I also saw that awslabs/aws-c-io#294 disables ALPN at compile time if Windows 7 support is requested, IIUC. Doesn't this mean that ALPN would not be used e.g. with Windows 10 when using a binary compiled with Windows 7 support?

The goal should be to have a binary that works with Windows 7 and Windows 10.

**Comment by justinboswell** [comment] 2020-07-10 22:57
> I see you made Windows 7 support behind a flag. Did you discover some problems having it on by default?

Yes. It changes behaviors for IOCP and thread scheduling. I'm currently investigating that further and looking to make it worth in both cases. As Win7 is past EOL for most users, we don't really want to default to that as the minspec, but I need it to work either way.

> I also saw that [awslabs/aws-c-io#294](https://github.com/awslabs/aws-c-io/pull/294) disables ALPN at compile time if Windows 7 support is requested, IIUC. Doesn't this mean that ALPN would not be used e.g. with Windows 10 when using a binary compiled with Windows 7 support?

That's correct, I'm working through the problem on Win7 first. That's still a draft PR. I'll get it working both ways.

**Comment by justinboswell** [comment] 2020-07-14 19:10
I/O changes have been merged, this library will be updated and a new release made shortly.

**Comment by rccarper** [comment] 2020-07-15 22:02
Changes should now be available in v0.8.8.

**Closed** 2020-07-15 22:02 UTC
Labels: feature-request, investigating
